### ISSUE TITLE
修正案

### ISSUE THREAD

**Issue by suzukiyukito** [c0b2116145/ProjExD#1]
https://github.com/c0b2116145/ProjExD/blob/193cd72261d844efa7ba4eaf60eee8d7d7a5a74c/ex01/dalphabet.py#L32

mc = 1 の部分をここに記載するより、初めにおいておくことによってmcがどのような変数であるか(初期設定であるのかの)区別がつくため、初めに書いた方がいいかも

**Comment by c0b2116145** [comment]
ありがとうございました。
