### ISSUE TITLE
ゴールの判定について

### ISSUE THREAD

**Issue by c0b21005c4** [c0b2116145/ProjExD#10]
https://github.com/c0b2116145/ProjExD/blob/64a12807fe333032d2cdef31821dee63be9a3588/ex03/maze.py#L91
ゴール判定を変えたほうが拡張性が出ると思います。例えばリストでゴールの部分の値を2にするなどすれば、大きさが変更されても扱うことができます。

**Comment by c0b2116145** [comment]
ありがとうございます

**Comment by c0b2116145** [comment]
提案していただいた方法は分からなかったので違う方法で修正しました
