### ISSUE TITLE
enemyについて

### ISSUE THREAD

**Issue by c0b21031** [c0b2116145/ProjExD#12]
https://github.com/c0b2116145/ProjExD/blob/64a12807fe333032d2cdef31821dee63be9a3588/ex03/maze.py#L24
まず迷路に敵キャラを設定してる時点ですごい。
特別修正点が見当たらないが、enemyのインスタンスを格納する変数が「_」なのがわかりづらかった。

**Comment by c0b2116145** [comment]
そんなに重要な変数ではないと感じたのでこのようにしました。
ご指摘ありがとうございました。
