### ISSUE TITLE
特に気になることはなかった

### ISSUE THREAD

**Issue by suzukiyukito** [c0b2116145/ProjExD#14]
しいて言うなら、while文でTrueを使う際に引数用いて扱うときとそうでないときがあるのが気になった。
https://github.com/c0b2116145/ProjExD/blob/590c128c44c616202975b8e7d692c112e5245e43/ex04/dodge_bomb.py#L168

**Comment by c0b2116145** [comment]
最初のwhile文はスペースキーを押されたときループから抜けれるようにしたかったから変数に入れた。
