### ISSUE TITLE
このコードについて

### ISSUE THREAD

**Issue by suzukiyukito** [c0b2116145/ProjExD#6]
このコードについて、n = ["+", "-", "÷", "*", "=", "CA", "因"]を用いているけど、これを辞書で表記すればより綺麗な条件分岐に表記しなおすことができるとおもう。
https://github.com/c0b2116145/ProjExD/blob/e1ea9e48841045c48f8abec74a200fe58345cebe/ex02/calc.py#L55

**Comment by c0b2116145** [comment]
ありがとうございました
