### ISSUE TITLE
これ実は二重for文を用いると簡単に表記できる

### ISSUE THREAD

**Issue by suzukiyukito** [c0b2116145/ProjExD#7]
for i in range(4):
    for j in range(3):
        num = 9-(j+i*3)
        if num >= 0:
            button = tk.Button(root,text=num,font=("Times New Roman",30),width=4,height=1)
            button.bind("<1>",button_click)
            button.grid(column=j,row =i+1)
のようにfor文で縦横の設定を定義することでより綺麗な表記表現になる
https://github.com/c0b2116145/ProjExD/blob/e1ea9e48841045c48f8abec74a200fe58345cebe/ex02/calc.py#L42

**Comment by c0b2116145** [comment]
サンプルコードまで丁寧に載せていただきありがとうございました。
